### ISSUE TITLE
TypeError: unable to convert a C++ 'QWebEngineFindTextResult' instance to a Python object

### ISSUE THREAD

**Issue by GuillaumeSeren** [qutebrowser/qutebrowser#5412]
**Version info**:

qutebrowser-1.11.0 or in master as cf4fb918fccb6c84bc6bfcd3693f50475ed03e17

**Does the bug happen if you start with `--temp-basedir`?**:
Same error.
**Description**
qutebrowser start at crash, was running fine with 1.10.1

**How to reproduce**

Start at crash,beside the error reporting qute never show up.

Some output when launching from terminal
```
20:33:17 ERROR: Uncaught exception
TypeError: unable to convert a C++ 'QWebEngineFindTextResult' instance to a Python object
^C20:34:04 INFO: SIGINT/SIGTERM received, shutting down!
```

**Comment by The-Compiler** [comment]
Can you please your full version info from `:version`?

**Comment by GuillaumeSeren** [comment]
Hello @The-Compiler thank you for the reply !

> Can you please your full version info from `:version`?

As it crash at startup, I can only provide `--version`

```
└─> qutebrowser --version
Git commit: cf4fb918f (2020-05-06 10:38:33 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.6.10
PyQt: 5.14.1

sip: 4.19.21
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.6.1
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-5.4.38-gentoo-x86_64-Intel-R-_Core-TM-_i7-6600U_CPU_@_2.60GHz-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3.6
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/gseren/.cache/qutebrowser
config: /home/gseren/.config/qutebrowser
data: /home/gseren/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/gseren/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
Ah, that works as well. I was expecting your PyQt version to be older than 5.14, but that doesn't seem the case... No idea what's going wrong there then. Can you hit "report" in the error reporting dialog so I can take a look at the logs?

**Comment by GuillaumeSeren** [comment]
Sent !

**Comment by The-Compiler** [comment]
Thanks! No stacktrace in there unfortunately... This is most likely related to #5352 - @Soul-Drake have you ever seen something like this?

**Comment by The-Compiler** [comment]
Oh, and @GuillaumeSeren, to confirm my suspicion: If you edit `/usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py` and in `_WebEngineSearchWrapHandler.connect_signal` (line 185) replace `if qtutils.version_check("5.14"):` with `if False:` - does the problem go away?

**Comment by GuillaumeSeren** [comment]
@The-Compiler yes that change fix the issue

```diff
--- /usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py    2020-05-06 23:35:49.060941466 +0200
+++ /usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab-fixed.py      2020-05-06 23:35:19.243728523 +0200
@@ -182,7 +182,8 @@ class _WebEngineSearchWrapHandler:
         Args:
             page: The QtWebEnginePage to connect to this handler.
         """
-        if qtutils.version_check("5.14"):
+        if False:
+            # if qtutils.version_check("5.14"):
    --- /usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py    2020-05-06 23:35:49.060941466 +0200
+++ /usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab-fixed.py      2020-05-06 23:35:19.243728523 +0200
@@ -182,7 +182,8 @@ class _WebEngineSearchWrapHandler:
         Args:
             page: The QtWebEnginePage to connect to this handler.
         """
-        if qtutils.version_check("5.14"):
+        if False:
+            # if qtutils.version_check("5.14"):
             page.findTextFinished.connect(self._store_match_data)
             self._nowrap_available = True
          page.findTextFinished.connect(self._store_match_data)
             self._nowrap_available = True
 
```

**Comment by Soul-Drake** [comment]
Huh. This seems to be happening outside of my code, somewhere in the sip/pyqt5 layer between qutebrowser and the C++ QtWebEngine backend. This never happened on my end, so I cross-checked the versions with mine - the only noticeable discrepancy I see is sip<5 and python=3.6. I checked the changelogs for sip and pyqt5 and couldn't find anything there nor on the pyqt mailinglist, and the pyqt documentation is [as helpful as ever](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtwebenginecore/qwebenginefindtextresult.html?highlight=qwebenginefindtext).

@The-Compiler you have more experience with these shenanigans than I do - is a failed C++ binding anything that's happened before? 

Maybe it's an issue with python versions (e.g. the python binding uses python 3.8-specific features? Seems unlikely.) I would recommend updating all packages to the latest versions, but that's going to be difficult if you're running Gentoo and they're not available yet.

**Comment by The-Compiler** [comment]
So far I've only seen this if e.g. a newer PyQt was compiled against an older Qt or something, which doesn't seem to be the case here... I suspect it's something Gentoo-specific, though I'm still not sure what exactly.

@GuillaumeSeren Can you confirm you get the same issue with this test script as well? Does anything change if you uncomment the pyqtSlot-line?

```python3
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QUrl, QTimer, pyqtSlot

app = QApplication([])

view = QWebEngineView()
view.load(QUrl('https://qutebrowser.org'))
view.show()

# @pyqtSlot('QWebEngineFindTextResult')
def slot(result):
    print(result.numberOfMatches())
    app.quit()

view.page().findTextFinished.connect(slot)
QTimer.singleShot(5000, lambda: view.findText("qutebrowser"))

app.exec_()
```

**Comment by GuillaumeSeren** [comment]
Hey @The-Compiler,
on the gentoo-specific side, it may but I use qutebrowser on gentoo for a long time,
qutebrowser still works fine with 1.10.1, this issue occur only on 1.11..0 and master.

I tested you script, it still crash with same error, bot with and without the comment
```
TypeError: unable to convert a C++ 'QWebEngineFindTextResult' instance to a Python object
```
But the timing is different, it show a working browser, and I can use it for a a few second (like 5s),
then crash, it is not exactly the same because on my issue the browser never show up, just the error dialog.

**Comment by The-Compiler** [comment]
FWIW the reason it happens immediately in qutebrowser is probably this call:

```
  .../qutebrowser/browser/webengine/webenginetab.py(1460)_on_load_started()
-> self.search.clear()
  .../qutebrowser/browser/webengine/webenginetab.py(314)clear()
-> self._widget.page().findText('')
> .../qutebrowser/browser/webengine/webenginetab.py(198)_store_match_data()
```

@GuillaumeSeren Some more questions:

- What does `python3 -c "from PyQt5.QtWebEngineCore import QWebEngineFindTextResult"` say?
- What are your package versions for `dev-python/PyQtWebEngine` and `dev-python/PyQt5`? Could it be possible that you're mixing PyQtWebEngine 5.13.* with PyQt5 5.14.*?

**Comment by GuillaumeSeren** [comment]
@The-Compiler 
>     * What does `python3 -c "from PyQt5.QtWebEngineCore import QWebEngineFindTextResult"` say?

```
└─> python3 -c "from PyQt5.QtWebEngineCore import QWebEngineFindTextResult"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'QWebEngineFindTextResult'
```

>     * What are your package versions for `dev-python/PyQtWebEngine` and `dev-python/PyQt5`?
dev-python/PyQtWebEngine-5.14.0
dev-python/PyQt5-5.14.1-r1

>     Could it be possible that you're mixing PyQtWebEngine 5.13.* with PyQt5 5.14.*?
Yes technically it is,
but as you see the installed version are 5.14 min.

**Comment by The-Compiler** [comment]
Ah, what about the `dev-qt/qtwebengine` package? Also, what does this say?

```
python3 -c "from PyQt5.QtWebEngine import PYQT_WEBENGINE_VERSION_STR; print(PYQT_WEBENGINE_VERSION_STR)"
```

**Comment by GuillaumeSeren** [comment]
@The-Compiler 

```
└─> python3 -c "from PyQt5.QtWebEngine import PYQT_WEBENGINE_VERSION_STR; print(PYQT_WEBENGINE_VERSION_STR)"
5.14.0
```

**Comment by The-Compiler** [comment]
You forgot the first part of the question :wink:

**Comment by GuillaumeSeren** [comment]
> You forgot the first part of the question wink

Ah sorry :)

dev-qt/qtwebengine-5.14.1

**Comment by The-Compiler** [comment]
Okay, so from what it seems, your PyQt has the `findTextFinished` signal, but doesn't know about the `QWebEngineFindTextResult` type. I have no idea why, because in PyQt, both are guarded by the same version guard:

```
%If (QtWebEngine_5_14_0 -)
    void findTextFinished(const QWebEngineFindTextResult &result);
%End
```

```
%If (QtWebEngine_5_14_0 -)

class QWebEngineFindTextResult
{
    // ...
};

%End
```

I've [posted to the PyQt mailinglist](https://www.riverbankcomputing.com/pipermail/pyqt/2020-May/042892.html) in the hope of finding out more. In the meantime, could  you please check whether this patch on top of v1.11.0 helps?

```patch
diff --git i/qutebrowser/browser/webengine/webenginetab.py w/qutebrowser/browser/webengine/webenginetab.py
index ffe227988..6b16a4d71 100644
--- i/qutebrowser/browser/webengine/webenginetab.py
+++ w/qutebrowser/browser/webengine/webenginetab.py
@@ -182,9 +182,16 @@ class _WebEngineSearchWrapHandler:
         Args:
             page: The QtWebEnginePage to connect to this handler.
         """
-        if qtutils.version_check("5.14"):
-            page.findTextFinished.connect(self._store_match_data)
-            self._nowrap_available = True
+        if not qtutils.version_check("5.14"):
+            return
+
+        try:
+            from PyQt5.QtWebEngineCore import QWebEngineFindTextResult
+        except ImportError:
+            return
+
+        page.findTextFinished.connect(self._store_match_data)
+        self._nowrap_available = True
 
     def _store_match_data(self, result):
         """Store information on the last match.
```

**Comment by Soul-Drake** [comment]
Maybe the installed versions are correct, but the order in which they were built created unfortunate version conflicts? (e.g. package A was upgraded to 14 while package B was at 13, so now it uses the version 13 interface with B even though B was since upgraded to 14 as well) - not sure to what degree pyqt and companions are vulnerable to these "linkage-type" problems, especially considering that portage _should_ deal with these issues.

**Comment by The-Compiler** [comment]
@Soul-Drake I still suspect something like that - and I've definitely seen similar issues when that happens, but so far that always was recognizable in the version information (for example, qutebrowser shows both the currently running Qt and the Qt version PyQt was compiled against, if they differ).

**Comment by Soul-Drake** [comment]
@GuillaumeSeren FYI, From the mailing list (see the full reply with @The-Compiler 's original post [here](https://www.riverbankcomputing.com/pipermail/pyqt/2020-May/042894.html)):

> I can't reproduce it with current versions - sounds like their build is 
> screwed.
>
> Phil

Could you try rebuilding all the relevant pyqt packages? At this point, it looks like this is probably a really unfortunate issue due to some mixup in the build process. If rebuilding / reinstalling the packages doesn't fix it, it may be worth informing the Gentoo maintainers of this.

**Comment by The-Compiler** [comment]
Yep - I'd be happy to add a workaround if my patch above works, but this is definitely something which also needs fixing either on your system or in Gentoo's packages.

**Comment by GuillaumeSeren** [comment]
Hey,
so much reply thank you a lot.

I was investigating my dev system to check if the issue was on my side,
so I rebuilded all the dependencies, and now it seems to works, even without the patch.

I am sorry for the false alarm, really appreciate the level of support of this project,
I will send the upgrade in gentoo.

Thank you :+1:

**Comment by The-Compiler** [comment]
Glad to hear! I'm closing this then, but if someone else happens to see the same, I'll add the workaround. Thanks for all the testing!

**Comment by The-Compiler** [comment]
FWIW this ended up happening to another Gentoo user in IRC, so I added a workaround printing a warning in da5d153dcd453263f59a80259ebda69b623a480c.

**Comment by GuillaumeSeren** [comment]
@The-Compiler you did well,
it is a strange bug, seem's some part of PyQtWebEngine didn't upgraded well,
but I wasn't sure it was only me, so maybe there is a real issue behind this.

I would interresting to gather more data, so please send user on the [gentoo bug tracker](url),
this way we could investigate why this is happening.

**Comment by mschilli87** [comment]
FWIW, this never happened to me and I use (and regularly update) qutebrowser on Gentoo for years.
Usually, there are a few updates without changes on the Qt site but if any Qt-related package can be updated, portage insist in updating them all and triggers a re-build of qutebrowser (just like it should).

**Comment by The-Compiler** [comment]
Looks like Fedora is affected somehow as well: #5517
