### ISSUE TITLE
Starting with --json-logging causes AttributeError

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6482]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 220, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 122, in run
    init(args=args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 157, in init
    _init_modules(args=args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 454, in _init_modules
    log.init_from_config(config.val)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/log.py", line 557, in init_from_config
    change_console_formatter(level)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/log.py", line 370, in change_console_formatter
    use_colors=old_formatter.use_colors)
AttributeError: 'JSONFormatter' object has no attribute 'use_colors'
```

on v2.2.2

**Comment by The-Compiler** [comment]
Bisected to 34822bb530a57aaa82420828ff6e630dfa1b5cd8:

```
commit 34822bb530a57aaa82420828ff6e630dfa1b5cd8
Author: Florian Bruhin <me@the-compiler.org>
Date:   Thu Jun 11 12:44:31 2020 +0200

    Change logging format when the loglevel is changed via config

 qutebrowser/utils/log.py     |  4 +++-
 tests/unit/utils/test_log.py | 19 ++++++++++++++++---
 2 files changed, 19 insertions(+), 4 deletions(-)
```
