### ISSUE TITLE
[qt6] Animations stop when there is no user input

### ISSUE THREAD

**Issue by TheHardew** [qutebrowser/qutebrowser#7532]
**Version info**:

I'm using the arch linux package, "qutebrowser-qt6-git"

qutebrowser v2.5.2
Git commit: 5ea48c6e7 on makepkg (2022-12-16 21:05:35 +0100)
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1 (compiled 6.4.0)

CPython: 3.10.8
PyQt: 6.4.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.1.81 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.0
QtNetwork SSL: OpenSSL 3.0.7 1 Nov 2022

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.1
Platform: Linux-6.0.12-zen1-1.1-zen-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/lizzie/.cache/qutebrowser
config: /home/lizzie/.config/qutebrowser
data: /home/lizzie/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/lizzie/.config/qutebrowser/config.py has been loaded
Uptime: 0:03:28

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Any "animated" content, like changing the website as new elements are being loaded in or videos or javascript animations stop when there is no user input. Moving the mouse or pressing keys makes qutebrowser start drawing changes again (usually just for a few seconds at most, but rarely the bug disappears).

Particulary problematic is the fact, that to watch any video you need to constanly provide an input and not every video on every site can be played with `yt-dlp`.
 
**How to reproduce**

Open any site, e.g. time.is. Stop providing any input. Most likeley the site will be blank. If it did load in, again, stop providing any input and no changes will be drawn. Might need to restart or create a new tab if the bug does not appear.

**Comment by illfygli** [comment]
I have the same problem recently, on my personal laptop running Arch.

No problem on work laptop with the same configuration, running an older version of `qutebrowser-qt6-bin`.

Compositor is Sway/wlroots.

Running `testbrowser_webengine.py time.is` shows the expected `Loading progress: x%` `Loading finished`, but the window is blank until I give it some input.

**Comment by TheHardew** [comment]
Also sway, package version `1:1.7-10.1`
With testbrowser the loading stops immediately when I press enter and I have to provide input to the browser window to make it load fully. Then the clock sometimes runs corerctly, sometimes stops after input is provided.

If I play a video, when the bug occurs no new frames are drawn, but audio is played without problem.

**Comment by illfygli** [comment]
`5afc8a681` is the last one that works for me.

Sifting through the merge that followed it. :)

**Comment by The-Compiler** [comment]
Huh, are you sure the environments (especially Qt versions) are otherwise identical? I don't see anything in qutebrowser that could affect this - even more so if it happens with the testbrowser as well, and certainly not in that merge (b4d32e04f42d0c4994a234105f01aabe0aba6ce0).

**Comment by illfygli** [comment]
Qt versions are the same, yes.

To run `5afc8a681`, I need pyqt5 installed for it to run though, so maybe it has something to do with that.

**Comment by TheHardew** [comment]
I can not replicate it using pyqt5 with the testbrowser fwiw

**Comment by mlmatlock** [comment]
Also using the qt6-git version from the AUR.

**Version info**:
qutebrowser v2.5.2
Git commit: 5ea48c6e7 on makepkg (2022-12-16 21:05:35 +0100)
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1 (compiled 6.4.0)

CPython: 3.10.8
PyQt: 6.4.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.1.81 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.0
QtNetwork SSL: OpenSSL 3.0.7 1 Nov 2022

Style: QFusionStyle
Platform plugin: wayland-egl
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.1
Platform: Linux-6.0.12-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/merell/.cache/qutebrowser
config: /home/merell/.config/qutebrowser
data: /home/merell/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/merell/.config/qutebrowser/config.py has been loaded
Uptime: 5:09:39 

Also happens to me normally, and with `--temp-basedir`.

While I don't seem to have a playback problem from news' sites, or YT in general, nothing loads until I provide _some_ input (mouse or key); sometimes twice or more to get a full load.

Particularly noticeable on mostly text sites (Arch's BBS and Wiki).  Even happening as I type this.

Using the testbrowser and _time.is_, I generally get a complete load, but then it freezes until an input is received.

I get bad freezes when trying to monitor my [ADSB feeds,](https://globe.adsbexchange.com)

**Comment by The-Compiler** [comment]
> Qt versions are the same, yes.
> 
> To run `5afc8a681`, I need pyqt5 installed for it to run though, so maybe it has something to do with that.

If you need PyQt5 installed, you're probably also *running* with Qt 5 rather than Qt 6, which means the Qt version definitely won't be the same :wink: `:version` should let you confirm that.

Could someone who's affected by this please try with `scripts/mkvenv.py --venv-dir .venv-pyqt63 --pyqt-version 6.3` and see if you can reproduce with `.venv-pyqt63/bin/python3 -m qutebrowser --temp-basedir` as well? Also, could you repeat that with `scripts/mkvenv.py --venv-dir .venv-pyqt64` and `.venv-pyqt64/bin/python3 -m qutebrowser --temp-basedir` to confirm that is indeed affected too?

**Comment by TheHardew** [comment]
`.venv-pyqt63/bin/python3 -m qutebrowser --temp-basedir` seems to not be affected. I did not test the others, but if its necessary I can.

**Comment by TheHardew** [comment]
6.4 is affected, 6.3 is not

**Comment by mlmatlock** [comment]
First, don't bite me...I'm one of those that just doesn't get programming/coding, so I'm blindly trying to follow along.

What am I doing wrong here?:

```
/usr/share/qutebrowser/scripts/mkvenv.py --venv-dir .venv-pyqt63 --pyqt-version 6.3
Traceback (most recent call last):
  File "/usr/share/qutebrowser/scripts/mkvenv.py", line 37, in <module>
    from scripts import utils, link_pyqt
ImportError: cannot import name 'link_pyqt' from 'scripts' (unknown location)
```

**Comment by TheHardew** [comment]
Seems the arch linux package does not come with this file. What I did was:
```
git clone https://github.com/qutebrowser/qutebrowser
cd qutebrowser
git checkout 5ea48c6e7
```
and then the commands given above

**Comment by TheHardew** [comment]
@mlmatlock did you use just `scripts/mkvenv.py --venv-dir .venv-pyqt64` or `scripts/mkvenv.py --venv-dir .venv-pyqt63 --pyqt-version 6.4`? you should be able to reproduce the bug with the second one

**Comment by mlmatlock** [comment]
@TheHardew, that was my problem.  :(

Ok, 6.4 has the 'bug' for me as well.

**Comment by liddqd** [comment]
works in venv with 6.3, can reproduce bug with venv and 6.4

arch linux 
sway 1:1.7-10

`qutebrowser v2.5.2
Git commit: 8decafefb on makepkg (2022-09-10 21:11:27 +1200)
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1 (compiled 6.4.0)

CPython: 3.10.9
PyQt: 6.4.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.11.2
yaml: 6.0
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.1.81 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.0
QtNetwork SSL: OpenSSL 3.0.7 1 Nov 2022

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.1
Platform: Linux-6.1.1-zen1-1-zen-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6`

**Comment by TheHardew** [comment]
Because it even happens with c++ I believe it's a qt bug and it should be posted to their bug tracker.  
I'm not sure if I should close this one, or keep it open so it's more visibe and people don't open new ones. For now I guess I'll keep it open.

**Comment by liddqd** [comment]
I am by no means an expert, but I agree that it is probably not in qute we will need to fix. I guess it could technically be in sway too, if its only sway users able to reproduce.

**Comment by The-Compiler** [comment]
I'll close this once it's reported upstream. I'll take a shot at trying to reproduce it in sway, and if I can, I'll report it upstream - if I can't, one of you will need to do so.

**Comment by The-Compiler** [comment]
Yup, trivial to reproduce under sway, and also [qtile](http://www.qtile.org/) when running with `qtile start -b wayland`. Both are using [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots), so I'm assuming anything using that will be affected.

Reported upstream: [[QTBUG-109775] [REG 6.3 -> 6.4] Rendering stops without user input with sway/wlroots - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-109775)

**Comment by The-Compiler** [comment]
In the upstream issue, someone mentions that:

> Well, I ran a system upgrade and I am no longer able to reproduce this.

Can anyone try to confirm this?

**Comment by mlmatlock** [comment]
I still need to provide some kind of input for time.is to increment; lasts a few seconds, then freezes again.

**Comment by liddqd** [comment]
I also am able to still reproduce

```qutebrowser v2.5.2
Git commit: f4f5ca266 on makepkg (2023-01-29 15:43:08 +0100)
Backend: QtWebEngine 6.4.2, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.2

CPython: 3.10.9
PyQt: 6.4.2

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.11.2
yaml: 6.0
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.2.146 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.1
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.4
Platform: Linux-6.1.9-zen1-1-zen-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/keel/.cache/qutebrowser
config: /home/keel/.config/qutebrowser
data: /home/keel/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/keel/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00```

**Comment by liddqd** [comment]
```qutebrowser v2.5.2
Git commit: https://github.com/qutebrowser/qutebrowser/commit/f4f5ca2663c3af79792c7741a02ddb0ebb37d0e1 on makepkg (2023-01-29 15:43:08 +0100)
Backend: QtWebEngine 6.4.2, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.2

CPython: 3.10.9
PyQt: 6.4.2

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.11.2
yaml: 6.0
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.2.146 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.1
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.4
Platform: Linux-6.1.9-zen1-1-zen-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00```

**Comment by mia-0** [comment]
My version of Mesa is slightly newer (22.3.5); maybe it’s that?

**Comment by liddqd** [comment]
I can no longer make qutebrowser launch in xwayland with env QT_QPA_PLATFORM=xcb (probably unrelated), but seemingly I  am no longer able to reproduce the bug after system upgrade with rebuild of qutebrowser-qt6-git.

Only related package I can see has been upgraded is sway. I am still on mesa 22.3.4.

```
[2023-02-19T19:32:03+0100] [ALPM] upgraded linux-firmware-whence (20230117.7e4f0ed-1 -> 20230210.bf4115c-1)
[2023-02-19T19:32:03+0100] [ALPM] upgraded linux-firmware (20230117.7e4f0ed-1 -> 20230210.bf4115c-1)
[2023-02-19T19:32:03+0100] [ALPM] upgraded linux-lts (5.15.93-1 -> 5.15.94-1)
[2023-02-19T19:32:04+0100] [ALPM] upgraded linux-zen (6.1.11.zen1-1 -> 6.1.12.zen1-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded linux-zen-headers (6.1.11.zen1-1 -> 6.1.12.zen1-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded thin-provisioning-tools (1.0.0-1 -> 1.0.2-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded lvm2 (2.03.18-4 -> 2.03.18-5)
[2023-02-19T19:32:05+0100] [ALPM] upgraded man-pages (6.02-1 -> 6.03-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded python-pip (22.3.1-1 -> 23.0.1-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded python-typing_extensions (4.4.0-1 -> 4.5.0-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded python-setuptools (1:67.2.0-1 -> 1:67.3.0-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded python-zipp (3.13.0-1 -> 3.14.0-1)
[2023-02-19T19:32:05+0100] [ALPM] upgraded sane (1.1.1-2 -> 1.2.1-3)
[2023-02-19T19:32:06+0100] [ALPM] upgraded signal-desktop (6.5.1-1 -> 6.6.0-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded sudo (1.9.12.p2-2 -> 1.9.13-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded sway (1:1.8-5 -> 1:1.8.1-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded systemd-resolvconf (252.5-1 -> 253-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded systemd-sysvcompat (252.5-1 -> 253-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded ttf-font-awesome (6.2.1-1 -> 6.3.0-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded webkit2gtk (2.38.4-1 -> 2.38.5-1)
[2023-02-19T19:32:06+0100] [ALPM] upgraded webkit2gtk-4.1 (2.38.4-1 -> 2.38.5-1)
[2023-02-19T19:32:07+0100] [ALPM] upgraded wine (8.1-1 -> 8.2-1)
[2023-02-19T19:32:07+0100] [ALPM] upgraded xorg-util-macros (1.19.3-1 -> 1.20.0-2)
[2023-02-19T19:32:07+0100] [ALPM] upgraded xterm (378-1 -> 379-1)
[2023-02-19T19:32:07+0100] [ALPM] upgraded yt-dlp (2023.01.06-1 -> 2023.02.17-1)
[2023-02-19T19:32:07+0100] [ALPM] upgraded zvbi (0.2.40-1 -> 0.2.41-1)
```

**Comment by liddqd** [comment]
I apologize, I am still able to reproduce. Qutebrowser was still being launched in xwayland, but my method of verifying if qute was in xwayland was flawed (xlsclients)-

**Comment by liddqd** [comment]
mesa 22.3.6 and I am no longer able to reproduce.

**Comment by mlmatlock** [comment]
Upgraded mesa works for me as well.  WooHoo!!!
