### ISSUE TITLE
PDF js crashes on hashOriginal.toHex is not a function

### ISSUE THREAD

**Issue by Pietagorh** [qutebrowser/qutebrowser#8859]
**Version info**:

```
qutebrowser v3.6.3
Git commit: 
Backend: QtWebEngine 6.10.2
  based on Chromium 134.0.6998.208
  with security patches up to 144.0.7559.96 (plus any distribution patches)
  (source: api)
Qt: 6.10.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes (after `:set content.pdfjs true`)

**Description**
Trying to open a PDF with PDF.js results in an error, the UI loads but not the document.
```
app.js:1371 An error occurred while loading the PDF.

PDF.js v5.4.624 (build: 384c6208b)
Message: hashOriginal.toHex is not a function
_otherError @ app.js:1371
util.js:509 Uncaught (in promise) UnknownErrorExceptiondetails: "TypeError: hashOriginal.toHex is not a function"message: "hashOriginal.toHex is not a function"name: "UnknownErrorException"stack: "Error\n    at BaseExceptionClosure (qute://pdfjs/build/pdf.mjs:425:29)\n    at qute://pdfjs/build/pdf.mjs:428:2"[[Prototype]]: Error
```
Worked great a week or 2 ago tho
tried with multiple different pdf's

**How to reproduce**

open a pdf with `content.pdfjs` set to `true`

**Comment by The-Compiler** [comment]
How did you install PDF.js? Looks like [toHex was added](https://caniuse.com/mdn-javascript_builtins_uint8array_tohex) with Chromium 140, so that will only work with the [upcoming Qt 6.11](https://wiki.qt.io/Qt_6.11_Release).

You should use the legacy build of PDF.js though, that will work just fine. That being said, I'll see if qutebrowser can polyfill it.

**Comment by Pietagorh** [comment]
> How did you install PDF.js? Looks like [toHex was added](https://caniuse.com/mdn-javascript_builtins_uint8array_tohex) with Chromium 140, so that will only work with the [upcoming Qt 6.11](https://wiki.qt.io/Qt_6.11_Release).
> 
> You should use the legacy build of PDF.js though, that will work just fine. That being said, I'll see if qutebrowser can polyfill it.

oop, i was indeed using the non-legacy arch package, i'll use that instead
ty for the fix tho

**Comment by Pietagorh** [comment]
> How did you install PDF.js? Looks like [toHex was added](https://caniuse.com/mdn-javascript_builtins_uint8array_tohex) with Chromium 140, so that will only work with the [upcoming Qt 6.11](https://wiki.qt.io/Qt_6.11_Release).
> 
> You should use the legacy build of PDF.js though, that will work just fine. That being said, I'll see if qutebrowser can polyfill it.

oop, i was indeed using the non-legacy arch package, i'll use that instead
ty for the fix tho

**Comment by Ezall2001** [comment]
```
09:09:21 ERROR: JS: [qute://pdfjs/build/pdf.mjs:7242] Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
09:09:21 ERROR: JS: [qute://pdfjs/web/viewer.mjs:5320] Uncaught TypeError: Cannot destructure property 'AbortException' of 'globalThis.pdfjsLib' as it is undefined.
09:09:21 ERROR: JS: [qute://pdfjs/web/viewer.html?filename=tmpp_h6qwdv_pdf-test.pdf&file=&source=https://www.orimi.com/pdf-test.pdf:1257] Uncaught TypeError: Cannot read properties of undefined (reading 'set')
```
I am getting this error even with the pdfjs-legacy

**Comment by code-hunger** [comment]
Thanks for the tip, installing pdfjs-legacy fixed the same issue for me on Manjaro.

**Comment by yessfan** [comment]
> ```
> 09:09:21 ERROR: JS: [qute://pdfjs/build/pdf.mjs:7242] Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
> 09:09:21 ERROR: JS: [qute://pdfjs/web/viewer.mjs:5320] Uncaught TypeError: Cannot destructure property 'AbortException' of 'globalThis.pdfjsLib' as it is undefined.
> 09:09:21 ERROR: JS: [qute://pdfjs/web/viewer.html?filename=tmpp_h6qwdv_pdf-test.pdf&file=&source=https://www.orimi.com/pdf-test.pdf:1257] Uncaught TypeError: Cannot read properties of undefined (reading 'set')
> ```
> 
> I am getting this error even with the pdfjs-legacy

I am also getting this error:
```
13:13:49 ERROR: JS: [qute://pdfjs/build/pdf.mjs:7242] Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
13:13:49 ERROR: JS: [qute://pdfjs/web/viewer.mjs:5320] Uncaught TypeError: Cannot destructure property 'AbortException' of 'globalThis.pdfjsLib' as it is undefined.
13:13:49 ERROR: JS: [qute://pdfjs/web/viewer.html?filename=tmp8exbleom_Winning_Ways_for_Your_Mathematical_Plays_V1.pdf&file=&source=https://mathwo.github.io/assets/files/penney_game/Winning_Ways_for_Your_Mathematical_Plays_V1.pdf:1257] Uncaught TypeError: Cannot read properties of undefined (reading 'set')
```

Should I open an issue for this?

**Comment by The-Compiler** [comment]
@Ezall2001 @yessfan See #8885

**Comment by ARK333333** [comment]
> How did you install PDF.js? Looks like [toHex was added](https://caniuse.com/mdn-javascript_builtins_uint8array_tohex) with Chromium 140, so that will only work with the [upcoming Qt 6.11](https://wiki.qt.io/Qt_6.11_Release).
> 
> You should use the legacy build of PDF.js though, that will work just fine. That being said, I'll see if qutebrowser can polyfill it.

updating Chromium fixed it for me
